version: "3"
services:
  apache-service: 
    container_name: "container-apache"
    build: .
    volumes: 
      - "volume-apache:/var/www/html"
    ports: 
      - "8080:80"
    restart: "unless-stopped"
    networks:
      - "networks-apache"

volumes:
  volume-apache:

networks:
  networks-apache:
